# This file was generated by scripts/gen-homebrew-formula.sh for v0.2.0 — do not edit.
class Wcode < Formula
  desc "Minimal coding agent CLI over OpenAI-compatible endpoints"
  homepage "https://github.com/WeiNyn/wcode"
  version "0.2.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/WeiNyn/wcode/releases/download/v0.2.0/wcode-v0.2.0-aarch64-apple-darwin.tar.gz"
      sha256 "bf04132ca4e9cd62fc6bfb0b11cf89a5e36dd97784e814b18c7182cd975e16ad"
    end
    on_intel do
      url "https://github.com/WeiNyn/wcode/releases/download/v0.2.0/wcode-v0.2.0-x86_64-apple-darwin.tar.gz"
      sha256 "e3fdb37508b04977407bf36d2c5ce451b3f78f06057e6226e9685b7f68fbe3dc"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/WeiNyn/wcode/releases/download/v0.2.0/wcode-v0.2.0-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "13ea5b9f3b2a0fba521cf38045743134c8129a0c1162d8133dfc995de5393b98"
    end
    on_intel do
      url "https://github.com/WeiNyn/wcode/releases/download/v0.2.0/wcode-v0.2.0-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "07348a11812f084f04ab9bcb47e095f31359d5799fd27389f603008e3d7c357b"
    end
  end

  def install
    bin.install "wcode"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/wcode --version")
  end

  livecheck do
    url :stable
    regex(/^v?(\d+(?:\.\d+)+)$/i)
  end
end
