# This file was generated by scripts/gen-homebrew-formula.sh for v0.5.0 — do not edit.
class Wcode < Formula
  desc "Minimal coding agent CLI over OpenAI-compatible endpoints"
  homepage "https://github.com/WeiNyn/wcode"
  version "0.5.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/WeiNyn/wcode/releases/download/v0.5.0/wcode-v0.5.0-aarch64-apple-darwin.tar.gz"
      sha256 "bf520645c78d0b689d1f2a9ffda4061512c5750873666940d480ae5a81598df6"
    end
    on_intel do
      url "https://github.com/WeiNyn/wcode/releases/download/v0.5.0/wcode-v0.5.0-x86_64-apple-darwin.tar.gz"
      sha256 "352fcbc7066787512fb5116ffb1d655931073ad44b05cd2ea647cbec24fc643b"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/WeiNyn/wcode/releases/download/v0.5.0/wcode-v0.5.0-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "5a83ef359dcab45c693af09cc5913a0dced72db58031d13b56cc51e68d3e1acb"
    end
    on_intel do
      url "https://github.com/WeiNyn/wcode/releases/download/v0.5.0/wcode-v0.5.0-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "08e1fc04a1103f758cd7cf167d5d5412877a8583968f9090384f67ee2952c702"
    end
  end

  def install
    bin.install "wcode"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/wcode --version")
  end

  livecheck do
    url :stable
    regex(/^v?(\d+(?:\.\d+)+)$/i)
  end
end
