# This file was generated by scripts/gen-homebrew-formula.sh for v0.3.1 — do not edit.
class Wcode < Formula
  desc "Minimal coding agent CLI over OpenAI-compatible endpoints"
  homepage "https://github.com/WeiNyn/wcode"
  version "0.3.1"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/WeiNyn/wcode/releases/download/v0.3.1/wcode-v0.3.1-aarch64-apple-darwin.tar.gz"
      sha256 "334b0c6af63ee4b4ef7818b1fb33083d22b518e335d4f11a679b45a659efddfa"
    end
    on_intel do
      url "https://github.com/WeiNyn/wcode/releases/download/v0.3.1/wcode-v0.3.1-x86_64-apple-darwin.tar.gz"
      sha256 "1c44a1015ab80ebbb22faecb93d19ff7795188b10551e11e8959451b158c4782"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/WeiNyn/wcode/releases/download/v0.3.1/wcode-v0.3.1-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "a3471e855ec32821224c870b929673b2bc3ae40cce72bff8b72405e5dd6bbd21"
    end
    on_intel do
      url "https://github.com/WeiNyn/wcode/releases/download/v0.3.1/wcode-v0.3.1-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "a38d403420bc47f3cefd95d17c7b8cd0886f6f1d40c7d7c43533d63dfcee9ab9"
    end
  end

  def install
    bin.install "wcode"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/wcode --version")
  end

  livecheck do
    url :stable
    regex(/^v?(\d+(?:\.\d+)+)$/i)
  end
end
