#!/usr/bin/env bash
#
# gen-homebrew-formula.sh — emit the Homebrew formula for a release tag.
#
#   usage: scripts/gen-homebrew-formula.sh <tag> [out-path]
#   e.g.:  scripts/gen-homebrew-formula.sh v0.2.0 Formula/wcode.rb
#
# Downloads each target's `.sha256` sibling (a bare hex digest, one line) from
# the GitHub release and writes a deterministic `Formula/wcode.rb`; with no
# out-path it prints to stdout. Fails loudly on a missing/empty checksum. No
# associative arrays, so it also runs under the bash 3.2 that ships on macOS.
set -euo pipefail

tag="${1:?usage: gen-homebrew-formula.sh <tag> [out-path]}"
out="${2:-}"

case "$tag" in
  v*) ;;
  *) echo "error: tag '${tag}' must start with 'v' (e.g. v0.2.0)" >&2; exit 1 ;;
esac
version="${tag#v}"

repo="WeiNyn/wcode"
homepage="https://github.com/WeiNyn/wcode"
base="https://github.com/${repo}/releases/download/${tag}"

# target -> its bare sha256 (first whitespace-separated field), lowercased.
sha_for() {
  local target="$1" s
  s="$(curl -fsSL "${base}/wcode-${tag}-${target}.sha256" | awk 'NR==1{print $1}')"
  [ -n "$s" ] || { echo "error: empty checksum for ${target}" >&2; exit 1; }
  s="$(printf '%s' "$s" | tr 'A-F' 'a-f')"
  case "$s" in
    *[!0-9a-f]*) echo "error: '${s}' is not a hex digest for ${target}" >&2; exit 1 ;;
  esac
  printf '%s' "$s"
}

mac_arm="$(sha_for aarch64-apple-darwin)"
mac_intel="$(sha_for x86_64-apple-darwin)"
linux_arm="$(sha_for aarch64-unknown-linux-gnu)"
linux_intel="$(sha_for x86_64-unknown-linux-gnu)"

formula="$(cat <<RUBY
# This file was generated by scripts/gen-homebrew-formula.sh for ${tag} — do not edit.
class Wcode < Formula
  desc "Minimal coding agent CLI over OpenAI-compatible endpoints"
  homepage "${homepage}"
  version "${version}"
  license "MIT"

  on_macos do
    on_arm do
      url "${base}/wcode-${tag}-aarch64-apple-darwin.tar.gz"
      sha256 "${mac_arm}"
    end
    on_intel do
      url "${base}/wcode-${tag}-x86_64-apple-darwin.tar.gz"
      sha256 "${mac_intel}"
    end
  end

  on_linux do
    on_arm do
      url "${base}/wcode-${tag}-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "${linux_arm}"
    end
    on_intel do
      url "${base}/wcode-${tag}-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "${linux_intel}"
    end
  end

  def install
    bin.install "wcode"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/wcode --version")
  end

  livecheck do
    url :stable
    regex(/^v?(\d+(?:\.\d+)+)$/i)
  end
end
RUBY
)"

if [ -n "$out" ]; then
  mkdir -p "$(dirname "$out")"
  printf '%s\n' "$formula" > "$out"
else
  printf '%s\n' "$formula"
fi
